lib/constructs/attribute.js
lib/constructs/interface.js
lib/constructs/iterable.js
lib/output/utils.js
package.json
test/cases/URL.idl
test/implementations/URLSearchParams.js

This is incomplete in the sense that it only supports pair iterators through iterable declaration (not value iterators, indexed property getter, maplike, or setlike); and it doesn't specifically handle mixins, overloading, etc. But I think this is a good start, and should cover a large swath of actual iterable API usage.

Implement pair iterators

---

.travis.yml
package.json
test/__snapshots__/test.js.snap
test/test.js

Previously we were just kind of running test/test.js as needed and hoping for the best. With this in place we have an easier way of checking for regressions.
Let's get Travis running on the PR first...

Add Jest-based snapshot testing and Travis

---

lib/constructs/attribute.js
lib/constructs/constant.js
lib/constructs/dictionary.js
lib/constructs/interface.js
lib/constructs/iterable.js
lib/constructs/operation.js
lib/context.js
lib/overloads.js
lib/parameters.js
lib/transformer.js
lib/types.js
package.json
test/__snapshots__/test.js.snap
test/cases/PromiseTypes.idl
test/cases/SeqAndRec.idl
test/cases/URL.idl
test/cases/URLSearchParams.idl
test/implementations/PromiseTypes.js
test/implementations/SeqAndRec.js
test/implementations/URL.js
test/implementations/URLSearchParams.js

Implementing union type conversion is next, followed by overload resolution algorithm (if need be).

Type conversion overhaul

---

lib/constructs/attribute.js
test/__snapshots__/test.js.snap

The CSS Object Model defines a [dashed attribute](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-dashed-attribute) on CSSStyleDeclaration, used like so:
`el.style["background-color"]`
This currently causes a syntax error in webidl2js since these keys can not be accessed through the dot notation. With this pull request, bracket notation is used instead. As far as I am aware the implications are only stylistic with no noticeable performance difference, so I've opted for using it for all properties rather than to look for problematic characters.

Use bracket notation to access implementation

---

lib/constructs/interface.js
lib/context.js
lib/output/interfaceStub.js
lib/overloads.js
lib/transformer.js
package-lock.json
test/__snapshots__/test.js.snap
test/implementations/PromiseTypes.js
test/implementations/TypedefsAndUnions.js
test/implementations/URL.js
test/implementations/URLSearchParams.js
test/implementations/Unforgeable.js
test/implementations/ZeroArgConstructor.js

- Variadic argument handling in "get effective override" imported straight from the spec
- Use Map instead of Object.create(null) for Context#dictionaries/interfaces, something I've wanted to do for quite some time
- Move Impl.init check to interface runtime, to simplify build process and eliminates circular dependencies. This does add a conditional to the generated files, but realistically the performance cost should be minimal.

Miscellaneous improvements

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

The Web IDL spec [suggests](https://heycam.github.io/webidl/#ref-for-sec-definepropertyorthrow%E2%91%A0) that for interface objects, the `writable` descriptor should be false. This change helps passing some IDL interface tests and appears to be consistent with current browsers. I've also tested the change in jsdom without errors.

Make the prototype of interface objects non-writable

---

README.md

Closes #1.
Also review from @Zirro would be cool; not sure why they're not part of the org yet. Will try to fix that.

Add a README documenting everything

---

lib/constructs/iterable.js
test/__snapshots__/test.js.snap

Use `Array.prototype[@@iterator]` instead because of https://github.com/tc39/ecma262/issues/695.

Do not use Array.prototype.values

---

README.md
lib/constructs/attribute.js
lib/constructs/constant.js
lib/constructs/interface.js
lib/constructs/iterable.js
lib/constructs/operation.js
lib/output/utils.js
lib/overloads.js
lib/utils.js
test/__snapshots__/test.js.snap
test/cases/MixedIn.idl
test/cases/Mixin.idl
test/cases/MixinInherited.idl
test/cases/MixinMixin.idl
test/cases/Overloads.idl
test/cases/Static.idl
test/cases/UnderscoredProperties.idl

This requires a change in jsdom to move idlUtils.mixin to jsdom, as it will no longer be needed or included in webidl2js. I could keep it in webidl2js for the time being however, until the next major bump.
Note, this does not yet fix https://github.com/jsdom/webidl2js/issues/55
Fixes #49.
Fixes #67.

Fix mixins, stringifiers, and static attributes

---

lib/constructs/attribute.js
lib/constructs/operation.js
test/__snapshots__/test.js.snap

I ran into the error `Impl.escape is not a function` while implementing the following IDL:
```webidl
interface CSS {
static CSSOMString escape(CSSOMString ident);
};
```
This pull request resolves the issue by using `Impl.implementation` rather than `Impl` directly. Given that I am not familiar with all parts of webidl2js, I'm not entirely convinced that this is the correct solution or merely one which obscures a larger issue.

Fix access to implementation of static operations

---

README.md

Document static operations/attributes

---

lib/constructs/interface.js
lib/output/utils.js
test/__snapshots__/test.js.snap

- Check the impl symbol is an own property of the received object.
- Make mixins' `.is()` methods use `iface.is()` instead of `instanceof
iface.interface`
- Add the interface's `.is()` to `.isMixedInto` of all consequential interfaces.
Fixes #62.

More accurate brand checks

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

A version of webkit doesn't allow new.target after a prefix operator.
Fixes #78.

Work around a webkit particularity

---

lib/transformer.js

Convert IDL and Impl directories to absolute paths before using them in addSource() and generate() as a fix for #80.
Ran npm test and everything passes.

Track IDL and Impl directories using absolute paths in transformer.js

---

test/__snapshots__/test.js.snap
test/cases/Reflect.webidl

There is no testcase involving `[Reflect]` at the moment, so I put together this IDL which covers the output in different scenarios.

Add testcase for [Reflect]

---

README.md
lib/constructs/interface.js
test/__snapshots__/test.js.snap
test/cases/Unscopable.webidl

This changed all the way back in https://github.com/heycam/webidl/issues/103.
It is a breaking change, though I doubt many will be affected.

[Unscopeable] is now [Unscopable]

---

lib/constructs/interface.js

`suppressErrors` is only intended to be used to suppress errors related to missing interface definitions, not a get-out-of-jail-free card for all situations.

Remove unnecessary usage of suppressErrors

---

README.md
lib/constructs/interface.js
lib/output/utils.js
test/__snapshots__/test.js.snap

We still support Node.js v6.x, which does not have `Object.getOwnPropertyDescriptors()`.

Provide polyfill for Object.getOwnPropertyDescriptors

---

lib/transformer.js
package.json

Fix also prettier warnings
> No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
cf discussion: https://github.com/Zirro/css-object-model/issues/10#issuecomment-398056931

add repo in package.json

---

README.md
lib/constructs/interface-mixin.js
lib/constructs/interface.js
lib/constructs/operation.js
lib/context.js
lib/transformer.js
package.json
test/__snapshots__/test.js.snap
test/cases/DOMImplementation.webidl
test/cases/MixedIn.webidl
test/cases/Unscopable.webidl
yarn.lock

~~Found that 10.3.0 doesn't break JSDOM while 10.3.1+ does.~~
Fixed the breakage faced in jsdom/jsdom#2443 so it's now safe to update to 10.3.1+.

chore(package): update webidl2

---

lib/constructs/attribute.js
lib/reflector.js
test/__snapshots__/test.js.snap

Following the discussion in https://github.com/jsdom/jsdom/pull/2546. The change has been tested with jsdom.
The `getAttribute()`-method includes a step that lowercases the attribute name while `getAttributeNS()` does not, so it is now done explicitly here. This is necessary for all tests in jsdom to pass.

Only reflect attributes without a namespace

---

lib/types.js
test/__snapshots__/test.js.snap

The WebIDL spec type-converts the key before retrieving the value. This is observable when providing a Proxy to this conversion. In that case [[GetOwnProperty]] should be called, but [[Get]] should not be observable.
By doing the key conversion before retrieving the value, we re-throw an error earlier and should be fine.

Fix operation ordering of record type coercions

---

lib/transformer.js
package.json
yarn.lock

This also gets rid of the security warning on GitHub.
----
Not upgrading webidl2.js though due to a multitude of issues we have yet with that.

Upgrade packages

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

Unscopable is supposed to have a null prototype.

Fix wrong prototype of unscopables

---

lib/reflector.js
test/__snapshots__/test.js.snap

This PR changes the way `[Reflect]` properties are generated. Instead of using the attribute methods on the wrapper, it uses the attributes methods on the impl.
More details here: https://github.com/jsdom/jsdom/issues/2158

Using impl attribute method for [Reflect] properties

---

.eslintrc.json
lib/transformer.js
package.json

Now that we dropped support for node 6, we remove the dependency on [`co`](https://www.npmjs.com/package/co), in favor of async/await.
As a side-effect, I also bumped the `emcaVersion` field on the `.eslintrc.json` to enable the usage of such syntax in the project.

Use async/await instead of co

---

lib/output/utils.js
lib/parameters.js
lib/types.js
package.json
test/__snapshots__/test.js.snap
test/cases/BufferSourceTypes.webidl
yarn.lock

Given jsdom's move to separate the Node.js globals from the JSDOM globals, instanceof is no longer reliable in this fashion.
Helps with https://github.com/jsdom/jsdom/pull/2743.
---
Probably I should also fix webidl-conversions before pulling this.

Avoid using instanceof for BufferSource types

---

lib/constructs/attribute.js
lib/constructs/dictionary.js
lib/constructs/enumeration.js
lib/constructs/interface.js
lib/constructs/iterable.js
lib/constructs/operation.js
test/__snapshots__/test.js.snap

Needed&nbsp;for&nbsp;<https://github.com/jsdom/jsdom/pull/2770> and&nbsp;converting&nbsp;`Window` to&nbsp;use&nbsp;**WebIDL** (<https://github.com/jsdom/jsdom/pull/2771>).
Re‑assigning&nbsp;`module.exports` breaks&nbsp;circular&nbsp;`require(…)`s, as&nbsp;any&nbsp;module that&nbsp;was&nbsp;evaluated before&nbsp;`module.exports` was&nbsp;re-assigned will&nbsp;keep the&nbsp;reference to&nbsp;the&nbsp;old&nbsp;object, which&nbsp;is&nbsp;still&nbsp;empty.
By&nbsp;instead creating&nbsp;data&nbsp;properties on&nbsp;`exports` and&nbsp;treating&nbsp;it as&nbsp;a&nbsp;constant, then&nbsp;every&nbsp;reference will&nbsp;have all&nbsp;the&nbsp;properties after&nbsp;all&nbsp;modules have&nbsp;been&nbsp;evaluated.
This&nbsp;is&nbsp;also&nbsp;closer to&nbsp;how&nbsp;**ECMAScript** modules&nbsp;work.

fix: Don’t break on circular imports

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

Currently, a&nbsp;new&nbsp;Proxy&nbsp;handler is&nbsp;created&nbsp;per‑instance, this&nbsp;is&nbsp;inefficient and&nbsp;unnecessary, especially&nbsp;since&nbsp;the&nbsp;proxy&nbsp;handlers don’t&nbsp;depend on&nbsp;any&nbsp;instance‑specific&nbsp;state.

perf(proxy): Use per‑class Proxy handler

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

Needed&nbsp;for&nbsp;<https://github.com/jsdom/jsdom/pull/2548>.
---
See&nbsp;also: <https://github.com/jsdom/webidl2js/pull/162>

fix: Expose `globalObject` on `proxyHandler` [CEReactions] methods

---

README.md
lib/constructs/interface.js
test/__snapshots__/test.js.snap

This removes the last of the old‑style mixin dead code that was not removed in <https://github.com/jsdom/webidl2js/pull/135>.

fix(interface): Remove dead code

---

lib/parameters.js
lib/types.js
test/__snapshots__/test.js.snap

This&nbsp;was&nbsp;encountered while&nbsp;working on&nbsp;<https://github.com/jsdom/jsdom/pull/2835>, where&nbsp;a&nbsp;circular&nbsp;dependency between&nbsp;`UIEvent` and&nbsp;`Window` causes&nbsp;`convertWindow` to&nbsp;be&nbsp;`undefined`.
I&nbsp;forgot to&nbsp;fix&nbsp;this in&nbsp;#154.

fix: Don’t break on circular type dependencies

---

README.md

`[PrimaryGlobal]` was removed from **WebIDL** in <https://github.com/heycam/webidl/pull/423> and from **WebIDL2JS** in commit [`112a4aa`](https://github.com/jsdom/webidl2js/commit/112a4aa57aaf9fbb5da4e7241b411e03bf25d036#diff-50e3aa130a4f97a42ee2cf111c7b1d9dL32-R32).

docs(README): Remove mentions of `[PrimaryGlobal]`

---

lib/transformer.js
package.json
yarn.lock

This removes the no longer necessary `pn/fs` dependency, like what was done in <https://github.com/jsdom/jsdom/pull/2783>.

fix: Use `fs.promises`

---

lib/output/utils.js

The&nbsp;current&nbsp;version needs&nbsp;to&nbsp;perform `[[Get]]`&nbsp;4&nbsp;times per&nbsp;invocation (5×&nbsp;when doing&nbsp;`idlUtils.hasOwn`).
The&nbsp;new&nbsp;version only&nbsp;performs&nbsp;it once&nbsp;during&nbsp;binding, which&nbsp;gives&nbsp;us performance&nbsp;gains:
<details>
<summary>Benchmark&nbsp;results</summary>
<p></p>
| benchmark                                                                                    | <code>Object&#x200B;.prototype&#x200B;.hasOwnProperty&#x200B;.call</code>                       | Bound&nbsp;`hasOwn`
| ---------                                                                                    | -------------------------------------------------------------------------                       | ---------
| …

perf: Use bound `hasOwn` helper

---

lib/constructs/attribute.js
lib/constructs/interface.js
lib/constructs/operation.js
test/__snapshots__/test.js.snap
test/cases/Global.webidl

This&nbsp;implements the&nbsp;`[ImplicitThis]`&nbsp;behaviour present&nbsp;on&nbsp;all WebIDL&nbsp;attributes and&nbsp;operations.
Needed&nbsp;for <https://github.com/jsdom/jsdom/pull/2835>
Will allow fixing <https://github.com/jsdom/jsdom/issues/2830>
See&nbsp;<https://github.com/heycam/webidl/pull/155> for&nbsp;details.

fix: Add `[ImplicitThis]` behaviour

---

.eslintrc.json
package.json
test/utils.test.js
yarn.lock

webidl-conversions now requires Node.js v10.x, which we already require anyway. Since 10.x adds BigInt support, we can remove the check for BigInt in our tests.

Upgrade dependencies; remove BigInt test

---

README.md
lib/constructs/attribute.js
lib/constructs/interface.js
lib/constructs/iterable.js
lib/constructs/operation.js
test/__snapshots__/test.js.snap

I’ve waited with opening this until after <https://github.com/jsdom/webidl2js/pull/166> was done to avoid merge conflicts.
This frees up the `impl` variable for use in <https://github.com/jsdom/webidl2js/pull/158> and also makes it clearer that the current `impl` variable refers to `implSymbol`.

refactor: Rename imported symbols

---

lib/context.js
lib/transformer.js
lib/types.js
test/__snapshots__/test.js.snap
test/cases/EventTarget.webidl

Implemented JS-to-IDL type conversion but not:
- Saving [callback context][1]
- [Call a user object's operation][2]
- IDL-to-JS type conversion (#71)
- [Legacy callback interface object][3]
Those things are left to more ambitious pull requests in the future.
Fixes https://github.com/jsdom/jsdom/issues/2869.
[1]: https://heycam.github.io/webidl/#dfn-callback-context
[2]: https://heycam.github.io/webidl/#call-a-user-objects-operation
[3]: https://heycam.github.io/webidl/#dfn-legacy-callback-interface-object
----
I've tested this by linking webidl2js in jsdom (also https://github.com/jsdom/jsdom/pull/2919) and it does fix https://github.com/jsdom/jsdom/issues/2869. Some things in this PR are gathered from elsewhere (like my own https://github.com/jsdom/webidl2js/pull/123). But others, like …

Preliminary support for callback interfaces

---

lib/constructs/callback-interface.js
test/__snapshots__/test.js.snap

I realised I forgot to do this after <https://github.com/jsdom/webidl2js/pull/172> was merged.

Ensure callback interfaces don’t leak implementation through `thisArg`

---

README.md
lib/constructs/interface.js
test/__snapshots__/test.js.snap
test/cases/CEReactions.webidl
test/cases/DOMRect.webidl
test/cases/Global.webidl
test/cases/HTMLConstructor.webidl
test/cases/URL.webidl

Fixes #187
---
review?(@TimothyGu)

Implement support for `[LegacyWindowAlias]` and `[NoInterfaceObject]`

---

README.md
lib/constructs/callback-interface.js
lib/constructs/interface.js
test/__snapshots__/test.js.snap

Extracted from <https://github.com/jsdom/webidl2js/pull/190> at @TimothyGu’s request in <https://github.com/jsdom/webidl2js/pull/191#pullrequestreview-387619767>.
This also fixes a bug where `install` takes `globalName` instead of `globalNames`.
---
This will free up <https://github.com/jsdom/webidl2js/pull/190> to only handle the creation of `webidl2js‑globals.js`.

Implement support for the `[Exposed]` extended attribute

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

This is not used by jsdom and seems unnecessary.

Remove undocumented Impl.init functionality

---

.eslintrc.json
README.md
lib/constructs/interface.js
test/__snapshots__/test.js.snap

Closes #193.
Since I had to do some refactoring to reduce duplication anyway, this also includes general cleanup to the output, such as replacing `obj` with either `value` or `wrapper`, using arrow functions for our exports, and such.
Ideas welcome on further refactoring to reduce duplication, but I think it's probably easiest to wait until we can stop exporting `setup()`; once that's true things become simpler.
On top of #195.

Add new() export for interfaces

---

lib/constructs/dictionary.js
lib/constructs/enumeration.js
test/__snapshots__/test.js.snap

Previously, we were comparing the original value with the set of possible enumeration values. This means values like { toString() { "valid-value" } } would not be allowed. Instead, we should check the post-string-conversion value.
Also changes the error messages generated in cases like these, from
> The provided value has member type that 'bytes' is not a valid enumeration value for ReadableStreamType
to
> The provided value has member 'type' that 'bytes' is not a valid enumeration value for ReadableStreamType
which is slightly better, although still not grammatical.

Fix treatment of non-strings as enumerations

---

README.md
lib/constructs/interface.js
test/__snapshots__/test.js.snap
test/cases/CEReactions.webidl
test/cases/HTMLConstructor.webidl

This is essentially a revert of f717fd45cbfc9fe05d3b03b430daf83504583a37, suitable for incorporation into the next major version.
@ExE-Boss your review on this one would be appreciated.
Also, if anyone has anything else backward-compat breaking we should bundle into v16 let me know.

Make [Exposed] and install()'s globalNames argument required

---

README.md
lib/constructs/attribute.js
lib/constructs/interface.js
lib/constructs/operation.js
lib/types.js
lib/utils.js
test/__snapshots__/test.js.snap
test/cases/DOMImplementation.webidl
test/cases/Global.webidl
test/cases/LegacyUnforgeable.webidl
test/cases/LegacyUnforgeableMap.webidl
test/cases/Unforgeable.webidl
test/cases/UnforgeableMap.webidl

I added a second commit for the renaming, so that you can see that the first commit does not effect the snapshot output at all.
Interestingly, we seem to support [LegacyLenientThis] and [LegacyOverrideBuiltins] with no tests.
This conflicts with #203; I will take care of the conflicts when merging, if both get approved.

Align with Web IDL extended attribute renames

---

README.md
lib/constructs/attribute.js
test/__snapshots__/test.js.snap
test/cases/LegacyLenientAttributes.webidl
test/cases/Replaceable.webidl

For [LegacyLenientThis], this fixes an issue where it would still try to get the impl value, even when the thisArg did not pass the is() check, resulting in a TypeError.
This also adds test coverage for [LegacyLenientThis] and [Replaceable], as part of #207.
---
This was originally #209 but that PR was sent from an organization and thus not acceptable for this project.

Implement [LegacyLenientSetter] and fix [LegacyLenientThis]

---

lib/constructs/attribute.js
lib/constructs/operation.js
test/__snapshots__/test.js.snap
test/cases/CEReactions.webidl
test/cases/Overloads.webidl
test/cases/PromiseTypes.webidl

Closes #79.
This removes support for overloading promise operations and non-promise operations, since that would require a more ambitious approach and doesn't seem to appear on the web.
---
Thoughts welcome. The strategy of using `async` for operations and try/catch for attributes makes the output nice but the webidl2js code a bit icky. Threading the async bit through all the operation stuff adds a bit of complexity. And, we might want to abandon that if we _do_ want to support overloads of promise-returning operations vs. non-promise returning ones, since doing that would require an appropriately-scoped try/catch.

Ensure promise-typed operations and attributes return promises

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

I noticed this while working on <https://github.com/jsdom/webidl2js/pull/213>.
---
review?(@domenic)

Fix `new(globalObject)` for legacy platform objects

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

Fixes <https://github.com/jsdom/webidl2js/issues/199>

Fix static attribute setters

---

lib/types.js
test/__snapshots__/test.js.snap

Most notably, this fixes the bug where rejected promises were being converted into resolved promises and that `Promise.resolve(x)` returns `x` when `x` is a `Promise` object from the same realm as the `Promise.resolve` function, whereas **WebIDL** requires the conversion to always return a new `Promise` object.
---
Note that there still is a small timing difference for non‑`void` promises due to the fact that the IDL conversion and promise reaction are being performed in separate `then` callbacks, whereas `WebIDL` runs them in the same `then` callback. (See the [“to **react** to a <code>Promise&lt;<var>T</var>&gt;</code>”](https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled) algorithm)
Fixing this minor timing discrepancy would require the type conversion …

Fix ECMAScript to IDL `Promise` type conversion

---

README.md
lib/constructs/interface.js
lib/constructs/operation.js
lib/utils.js
test/__snapshots__/test.js.snap
test/cases/DOMRect.webidl

This is necessary to be able to implement `DOMRect.fromRect(…)` in **JSDOM**.
---
Fixes <https://github.com/jsdom/webidl2js/issues/186>
review?(@domenic, @TimothyGu)

Implement [WebIDL2JSCallWithGlobal] for static operations

---

lib/constructs/attribute.js
lib/constructs/iterable.js
lib/constructs/operation.js
test/__snapshots__/test.js.snap

The improved error message format is based on the one used in **Firefox**.
---
Related to <https://github.com/jsdom/webidl2js/issues/204> and <https://github.com/jsdom/webidl2js/issues/217>.

Improve “Illegal invocation” error messages

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

This fixes the legacy platform object `[[Set]]` operation implementation to match the **WebIDL** spec, which doesn’t exclude array index properties from named properties when indexed setters aren't supported.
---
It also fixes the bug that was caused by the `receiver` argument in a Proxy trap pointing to the Proxy exotic object or an object that inherits from it, rather than to the underlying Proxy target.
This can be verified with:
```js
(new Proxy({}, { get(target,_,receiver) { console.log(target === receiver); } })).foo;
```
Which logs `false`.
---
review?(@domenic)

Fix legacy platform object [[Set]] operation

---

lib/parameters.js
test/__snapshots__/test.js.snap
test/cases/DOMRect.webidl
test/cases/DictionaryConvert.webidl

In Web IDL these days, optional dictionary arguments must have a trailing "= {}". This adds those to the test .webidl files. Doing so uncovered an issue where DOMRectInit was referenced in the test files, but did not exist, so we add code to throw in this case, and correct the test file.

Tweak test cases for dictionary defaults

---

test/__snapshots__/test.js.snap
test/test.js

There are two top‑level tests named `"utils.js"`, one is a `describe` in `utils.test.js`, the other is in `test.js`, this is generally un‑advised.
- <https://github.com/jsdom/webidl2js/pull/126>
---
Best reviewed with whitespace‑only changes hidden: [#170?w=1](https://github.com/jsdom/webidl2js/pull/170/files?w=1#diff-a561630bb56b82342bc66697aee2ad96efddcbc9d150665abd6fb7ecb7c0ab2f)

Wrap generation test file in a `describe`

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap
test/cases/LegacyNoInterfaceObject.webidl

See <https://github.com/heycam/webidl/issues/919> and <https://github.com/heycam/webidl/pull/920>.
---
Also covers part of <https://github.com/jsdom/webidl2js/issues/207>.

Require [Exposed] even when marked as [LegacyNoInterfaceObject]

---

lib/constructs/interface.js

The `parent` property was added to the AST in [**WebIDL2** v2.10.0](https://github.com/w3c/webidl2.js/blob/gh-pages/CHANGELOG.md#v23100-2019-10-14) in <https://github.com/w3c/webidl2.js/pull/425>.

Use `member.parent.name` instead of `member.definingInterface`

---

lib/constructs/async-iterable.js
lib/constructs/interface.js
lib/constructs/iterable.js
lib/output/utils.js
test/__snapshots__/test.js.snap

See <https://github.com/jsdom/jsdom/issues/2727> and <https://github.com/jsdom/jsdom/issues/2727#issuecomment-787559889>.

Create sync iterators in the correct realm

---

lib/constructs/callback-function.js
lib/constructs/interface.js
test/__snapshots__/test.js.snap

These would often cause runtime failures anyway. Generating nicer error messages for such runtime failures is not worth the cost in generated code size, especially given that such scenarios indicate a coding failure on the part of the user of webidl2js, not the user of jsdom.

Remove extra checks from generated code

---

README.md
lib/constructs/interface.js
test/__snapshots__/test.js.snap

Extracted from <https://github.com/jsdom/webidl2js/pull/213> because of <https://github.com/jsdom/webidl2js/pull/213#issuecomment-792345633>:
> The generated snapshots here seem overcomplicated, and it's not clear why you're modifying existing functionality (like `new()`).
- <https://github.com/jsdom/webidl2js/pull/213>

Implement “internally create a new object implementing the interface”

---

lib/constructs/attribute.js
lib/constructs/interface.js
lib/constructs/operation.js
lib/output/utils.js
lib/utils.js
test/__snapshots__/test.js.snap

This makes it so that:
```js
console.assert(new Event("foo").__lookupGetter__("isTrusted") === new Event("bar").__lookupGetter__("isTrusted"));
```
Which passes in browsers.
<dl>
<dt><a href="https://heycam.github.io/webidl/#create-an-interface-object">create an interface object</a></dt>
<dd>
> 5. Let <var>unforgeables</var> be [!] [OrdinaryObjectCreate]\(<b>null</b>\).
> 6. [Define the unforgeable regular operations] of <var>I</var> on <var>unforgeables</var>, given <var>realm</var>.
> 7. [Define the unforgeable regular attributes] of <var>I</var> on <var>unforgeables</var>, given <var>realm</var>.
> 8. Set <var>F</var>.[[Unforgeables]] to <var>unforgeables</var>.
</dd>
<dt><a href="https://heycam.github.io/webidl/#internally-create-a-new-object-implementing-the-interface">internally …

Use `[[Unforgeables]]` object for unforgeable properties

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap

I realised while working on <https://github.com/jsdom/webidl2js/pull/242> that in <https://github.com/jsdom/webidl2js/pull/234>, the `AsyncIterator` subclass is created wrongly, because the object that should be passed to `Object.assign` is instead accidentally passed as an excess parameter to `Object.create`.
---
This also makes it use `utils.define` now that it exists as of <https://github.com/jsdom/webidl2js/pull/226>.

fixup! Create sync iterators in the correct realm

---

.github/workflows/build.yml
lib/constructs/callback-function.js
lib/constructs/callback-interface.js
lib/context.js
lib/types.js
package.json
test/cases/BufferSourceTypes.webidl
test/cases/CEReactions.webidl
test/cases/Enum.webidl
test/cases/EventListener.webidl
test/cases/EventTarget.webidl
test/cases/Global.webidl
test/cases/LegacyUnforgeable.webidl
test/cases/PromiseTypes.webidl
test/cases/SeqAndRec.webidl
test/cases/Storage.webidl
test/cases/TypedefsAndUnions.webidl
test/cases/URLSearchParams.webidl
test/cases/URLSearchParamsCollection2.webidl
test/cases/UnderscoredProperties.webidl
test/cases/Variadic.webidl
yarn.lock

This notably includes updates for void → undefined, and causes us to start requiring Node.js v12 since the webidl-conversions dependency now does.
Closes #249.

Update dependencies and dev dependencies

---

README.md
lib/constructs/interface.js
lib/output/utils.js
test/__snapshots__/test.js.snap
test/utils.test.js

This PR intends to allow webidl2js to use the correct realm's `AsyncIteratorPrototype`. It uses a structure similar to https://github.com/jsdom/webidl2js/pull/234, registering an `AsyncIteratorPrototype` in each global object's `ctorRegistry` and inheriting from that prototype in `install()`.
#234 obtained the `IteratorPrototype` from `globalObject.Array`; unfortunately, afaik there are no ecmascript globals that link to the `AsyncIteratorPrototype`, so that approach is not possible here.
~~This PR exposes a utility, `registerConstructor(globalObject, key, constructor)` (bikeshedding appreciated), which sets a binding in the `globalObject`'s `ctorRegistry`. Consumers can use this to register the correct `AsyncIteratorPrototype` prior to installing interfaces on their global object, using …

Create async iterators and iterator result objects in the correct realm

---

lib/constructs/interface.js
test/__snapshots__/test.js.snap
test/cases/HTMLCollection.webidl
test/cases/HTMLFormControlsCollection.webidl

https://github.com/jsdom/webidl2js/issues/113

allow getters, setters and deleters to be shadowed in derived class

---

lib/constructs/interface.js
lib/output/utils.js
test/__snapshots__/test.js.snap

Fixes https://github.com/jsdom/jsdom/issues/3565.

Fix generated set trap for proxy cases
