jsdom/webidl2js

- lib/constructs/attribute.js
- lib/output/utils.js
Thanks for helping out with the code.
> Support the [SameObject] extended attribute

- lib/constructs/interface.js
- lib/constructs/iterable.js
- lib/utils.js
See https://github.com/tmpvar/jsdom/pull/1734#discussion_r100679464
A patch for jsdom is available at https://github.com/TimothyGu/jsdom/commit/ce679c3489263c99a4e14a6cd1e93751b141a4df
> Try to automatically wrap iterated key/value

- lib/types.js
- test/__snapshots__/test.js.snap
> Include symbol properties in record processing

- lib/constructs/attribute.js
- lib/constructs/constant.js
- lib/constructs/dictionary.js
- lib/constructs/interface.js
- lib/constructs/iterable.js
- lib/constructs/operation.js
- lib/context.js
- lib/output/utils.js
- lib/parameters.js
- lib/transformer.js
- lib/types.js
- lib/utils.js
- test/__snapshots__/test.js.snap
- test/cases/Storage.idl
- test/cases/URLList.idl
- test/cases/URLSearchParamsCollection.idl
- test/cases/URLSearchParamsCollection2.idl
- test/cases/UnforgeableMap.idl
Companion jsdom PR: https://github.com/tmpvar/jsdom/pull/1934
> Implement legacy platform object + others

- lib/constructs/interface.js
- test/__snapshots__/test.js.snap
- test/cases/LegacyArrayClass.idl
This implements [LegacyArrayClass](https://heycam.github.io/webidl/#LegacyArrayClass), and has been tested through my CSSOM-implementation.
> Add support for [LegacyArrayClass]

- README.md
@TimothyGu please feel free to help out by pushing commits to this branch.
> Add documentation for named/indexed properties [WIP]

- README.md
- lib/parameters.js
- test/__snapshots__/test.js.snap
- test/cases/Variadic.idl
> Add simple variadic operation support

- README.md
- lib/constructs/attribute.js
- lib/constructs/enumeration.js
- lib/context.js
- lib/transformer.js
- lib/types.js
- test/__snapshots__/test.js.snap
- test/cases/Enum.webidl
- test/cases/RequestDestination.webidl
- test/cases/TypedefsAndUnions.webidl
> Add support for enumeration types

- lib/output/utils.js
> Remove getReferenceToBytes/getCopyToBytes in utils

- lib/constructs/interface.js
- test/__snapshots__/test.js.snap
> Update iterator class string

- lib/constructs/interface.js
- test/__snapshots__/test.js.snap
Regression since 112a4aa57aaf9fbb5da4e7241b411e03bf25d036. Spotted by @domenic.
> Allow interfaces to be subclassable

- README.md
- lib/constructs/interface-mixin.js
- lib/constructs/interface.js
- lib/context.js
- lib/transformer.js
- package.json
- test/__snapshots__/test.js.snap
- test/cases/MixedIn.webidl
- yarn.lock
> Support interface mixins and includes statements

- README.md
- test/cases/Factory.webidl
- test/cases/URLSearchParamsCollection.webidl
> Escape certain reserved identifiers

- README.md
This has been annoying me for years.
> docs(readme): Fix `createImpl(…)` description

- .travis.yml
- lib/constructs/interface.js
- lib/output/utils.js
- package.json
- test/__snapshots__/test.js.snap
* Remove `Object.getOwnPropertyDescriptors` polyfill
* Raise min Node version to 8
Fixes #112.
> Retire Object.getOwnPropertyDescriptors polyfill

- README.md
- lib/constructs/interface.js
- lib/keywords.js
- lib/transformer.js
- test/__snapshots__/test.js.snap
- test/cases/MixedIn.webidl
- test/cases/Mixin.webidl
- test/cases/MixinInherited.webidl
- test/cases/MixinMixin.webidl
- test/cases/UnderscoredProperties.webidl
> Remove old-style mixins

- package.json
- test/__snapshots__/test.js.snap
- yarn.lock
The prettier update apparently changes the output slightly.
> Upgrade Prettier and ESLint

- lib/parameters.js
- lib/types.js
> Remove support for exception types

- .eslintrc.json
- test/test.js
- test/utils.test.js
This&nbsp;adds&nbsp;tests for&nbsp;the&nbsp;`utils.js`&nbsp;file.
> test(utils): Add tests for utils

- package.json
- yarn.lock
> Update dependencies and regenerate yarn.lock

- lib/constructs/dictionary.js
- test/__snapshots__/test.js.snap
> refactor(dictionary): Rename `convertInherit`

- README.md
- lib/constructs/interface.js
- test/__snapshots__/test.js.snap
- test/cases/CEReactions.webidl
- test/cases/HTMLConstructor.webidl
This takes a different approach than #201, which is less clean code-wise, but perhaps better release-wise. After all, #201 removes features that were released, which is arguably itself a major version bump...
> A different attempt to fix the v15 release line to not be backward-compat breaking

- lib/constructs/interface.js
- test/__snapshots__/test.js.snap
I realised that I forgot about this only after <https://github.com/jsdom/webidl2js/pull/234> was merged.
> fixup! Create sync iterators in the correct realm
